app:
  name: "my-python-application"
  version: "1.0.0"

server:
  host: "0.0.0.0"
  port: 8000

database:
  url: "sqlite:///./test.db"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
